# Este flujo de trabajo construirá y desplegará la aplicación Spring Boot a Docker Hub y luego a AWS ECS

name: Build & Deploy Spring app

# Define cuándo se ejecutará el flujo de trabajo
on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    env: # Define las variables de entorno aquí
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      PROJECT_SECRET_KEY: ${{ secrets.PROJECT_SECRET_KEY }}
      PROJECT_FRONTEND_PATH: ${{ secrets.PROJECT_FRONTEND_PATH }}


    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17


      - name: Unit Tests
        run: mvn -B test --file pom.xml


      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml


      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/menueasy:today


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/menueasy:today


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'


      - name: Build, Tag and Deploy to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT


      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v@1
        with:
          task-definition: task-definition.json
          container-name: menueasy
          image: ${{ steps.build-image.outputs.image }}


      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: menueasy-service
          cluster: DevCluster2
          wait-for-service-stability: true