# documentation.
name: MenuEasy CI with maven

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  pull_request:
    branches: [ "main" ]
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v3
       with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
     - name: Build and run Unit/Integration Tests with Maven
       run: mvn -ntp -B verify

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: cristianlopezcma/adsoproject-github
        tags: latest
        registry: docker.io
        dockerfile: backend/Dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
     
