name: Deploy frontend application to Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-cd.yml'

jobs:
  deploy-to-eb:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.0'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Build the application
        run: zip -r frontend.zip .

      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT